spring:
  mail:
    host: smtp.qq.com
    username: 3050155174@qq.com
    password: bnapzrrhtuxldcei
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小、最小、最大连接数
      initial-size: 5
      min-idle: 5
      max-active: 20

      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000

      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

      # 测试连接是否可用的SQL
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # 配置监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.tao.entity.pojo
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
